export const SET_BEER = 'SET_BEER';

export const ADD_TO_CART = 'ADD_TO_CART';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const EMPTY_THE_CART = 'EMPTY_THE_CART';

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const SET_FORM_STATUS = 'SET_FORM_STATUS';

export const SET_AUTHORIZATION_STATUS = 'SET_AUTHORIZATION_STATUS';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
